
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fymmlsoylacrkdeauxup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bW1sc295bGFjcmtkZWF1eHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTIxNTQsImV4cCI6MjA2MDE4ODE1NH0.z2niCXogmohm5Z3iuualEp4r4-oeb585IM5Tl2_qQ-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
